apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-postgres
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-postgres
  template:
    metadata:
      labels:
        app: zabbix-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: zabbix
            - name: POSTGRES_PASSWORD
              value: zabbix_pass
            - name: POSTGRES_DB
              value: zabbix
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: zabbix-postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432
