apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-proxy
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-proxy
  template:
    metadata:
      labels:
        app: zabbix-proxy
    spec:
      containers:
        - name: zabbix-proxy
          image: zabbix/zabbix-proxy-mysql:7.4.13-ubuntu
          env:
            - name: DB_SERVER_HOST
              value: zabbix-mysql
            - name: MYSQL_USER
              value: zabbix
            - name: MYSQL_PASSWORD
              value: zabbix_pass
            - name: MYSQL_DATABASE
              value: zabbix_proxy
            - name: ZBX_SERVER_HOST
              value: zabbix-server
            - name: ZBX_HOSTNAME
              value: zabbix-proxy     # nome único do proxy            
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: zabbix-proxy-data
              mountPath: /var/lib/zabbix
      volumes:
        - name: zabbix-proxy-data
          persistentVolumeClaim:
            claimName: zabbix-proxy-data-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-proxy-data-pvc
  namespace: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-proxy
  namespace: argocd
spec:
  selector:
    app: zabbix-proxy
  ports:
    - port: 10050
      targetPort: 10050
  type: ClusterIP
